---
sidebar: sidebar 
permalink: concept-cvs-gcp.html 
keywords: cloud volumes service for gcp, google cloud, cloud volumes, cloud volumes service subscription 
summary: O NetApp Cloud Volumes Service para Google Cloud permite adicionar rapidamente cargas de trabalho multiprotocolo, bem como criar e implantar aplicativos baseados em Windows e UNIX. 
---
= Saiba mais sobre o Cloud Volumes Service
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O NetApp Cloud Volumes Service para Google Cloud permite adicionar rapidamente cargas de trabalho multiprotocolo, bem como criar e implantar aplicativos baseados em Windows e UNIX.



== Principais recursos

* Migre dados entre o local e o Google Cloud.
* Provisionar volumes de 1 a 100 TIB em segundos.
* Suporte a vários protocolos (você pode criar um volume NFS ou SMB).
* Proteger dados com snapshots automatizados e eficientes.
* Acelerar o desenvolvimento de aplicações com clonagem rápida.




== Custo

Os volumes criados pelo Cloud Volumes Service para Google Cloud são cobrados na sua subscrição do serviço, não pelo BlueXP .

Não há cobrança para descobrir uma região ou volume do Cloud Volumes Service para o Google Cloud da BlueXP .

link:https://console.cloud.google.com/marketplace/product/endpoints/cloudvolumesgcp-api.netapp.com?q=cloud%20volumes%20service["Veja preços no Google Cloud Marketplace"^]



== Regiões suportadas

https://cloud.netapp.com/cloud-volumes-global-regions#cvsGc["Veja regiões compatíveis do Google Cloud"^]



== Antes de começar

O BlueXP  pode descobrir assinaturas e volumes existentes do Cloud Volumes Service para Google Cloud. Consulte o https://cloud.google.com/solutions/partners/netapp-cloud-volumes/["Documentação do NetApp Cloud Volumes Service para Google Cloud"^] se ainda não tiver configurado a sua subscrição.



== Obter ajuda

Use o bate-papo do BlueXP  para perguntas gerais sobre a operação do Cloud Volumes Service no BlueXP .

Para perguntas gerais sobre o Cloud Volumes Service, envie um e-mail para a equipe do NetApp em NetApp.com.

Para problemas técnicos associados ao Cloud volumes, você pode criar um caso de suporte técnico no Google Cloud Console. link:https://cloud.google.com/solutions/partners/netapp-cloud-volumes/support["obtenção de apoio"^]Consulte para obter detalhes.



== Links relacionados

* https://cloud.netapp.com/cloud-volumes-service-for-gcp["NetApp BlueXP : Cloud Volumes Service para Google Cloud"^]
* https://cloud.google.com/solutions/partners/netapp-cloud-volumes/["Documentação do NetApp Cloud Volumes Service para Google Cloud"^]

